[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar app.jar"
# healthcheckPath = "/inktracks/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3